[package]
name = "bevy_playground"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bevy = "0.7"
rand = "0.8"

[profile.dev.package."*"]
opt-level = 3

